### ISSUE TITLE
Problems with upcoming Funkwhale 1.2

### ISSUE THREAD

**Issue by georgkrause** [thetarkus/docker-funkwhale#59]
Hello,

I noticed that the changes we made for the upcoming Funkwhale 1.2 lead to break the built of the All-in-one-Container. See for example here: https://dev.funkwhale.audio/funkwhale/funkwhale/-/jobs/66774

I am currently not sure how the cooperation between his project and Funkwhale is organized. It seems like Funkwhale officially provides the built images, but we are not fully in control of the source code, or at least I don't have the possibility to commit here. I'd be open to discuss a migration of the project in our Gitlab. Anyway, this is not our project and I don't intent to force you to do anything :)

Back to topic: I updated a huge set of dependencies, some require some additional build tools, so it should be done with some minor changes. I can help with spotting these needed changes.

**Comment by agateblue** [comment]
Hi @michaelmob, I can confirm @georgkrause is one of the new maintainers of the Funkwhale project and community (you can have a look at https://blog.funkwhale.audio/~/Announcements/Current%20state%20of%20finding%20new%20maintainers for more context, basically I'm stepping down for personal reasons and @georgkrause and others community members decided to step up).

Since, IIRC, you moved on to other activities yourself and would rather not maintain this project (not 100% sure of that, but I got this feeling from our last interactions), maybe moving this repo to our Gitlab instance, as suggested by @georgkrause, would help you with that?

@michaelmob I don't think I've ever thanked you properly for your work on this image. It really helped a lot of people, setting up the project, including myself. I am very grateful for that. I hope you're fine and I wish you the best.

Take care

**Comment by georgkrause** [comment]
Closing this because the project doesn't seem to be actively maintained anymore and we dropped support for All-In-One-Images
